#include "TagAndProbe/Analysis/interface/LeptonTree.h"
LeptonTree lepton_tree_obj;
namespace lepton_tree {
	const float &evt_pfmet() { return lepton_tree_obj.evt_pfmet(); }
	const float &evt_pfmetPhi() { return lepton_tree_obj.evt_pfmetPhi(); }
	const float &evt_trackmet() { return lepton_tree_obj.evt_trackmet(); }
	const float &evt_trackmetPhi() { return lepton_tree_obj.evt_trackmetPhi(); }
	const float &evt_corrMET() { return lepton_tree_obj.evt_corrMET(); }
	const float &evt_corrMETPhi() { return lepton_tree_obj.evt_corrMETPhi(); }
	const float &evt_pfsumet() { return lepton_tree_obj.evt_pfsumet(); }
	const float &evt_pfmetSig() { return lepton_tree_obj.evt_pfmetSig(); }
	const int &evt_event() { return lepton_tree_obj.evt_event(); }
	const int &evt_lumiBlock() { return lepton_tree_obj.evt_lumiBlock(); }
	const int &evt_run() { return lepton_tree_obj.evt_run(); }
	const bool &filt_csc() { return lepton_tree_obj.filt_csc(); }
	const bool &filt_hbhe() { return lepton_tree_obj.filt_hbhe(); }
	const bool &passes_met_filters() { return lepton_tree_obj.passes_met_filters(); }
	const bool &filt_hcallaser() { return lepton_tree_obj.filt_hcallaser(); }
	const bool &filt_ecaltp() { return lepton_tree_obj.filt_ecaltp(); }
	const bool &filt_trkfail() { return lepton_tree_obj.filt_trkfail(); }
	const bool &filt_eebadsc() { return lepton_tree_obj.filt_eebadsc(); }
	const bool &evt_isRealData() { return lepton_tree_obj.evt_isRealData(); }
	const float &scale1fb() { return lepton_tree_obj.scale1fb(); }
	const float &evt_xsec_incl() { return lepton_tree_obj.evt_xsec_incl(); }
	const float &evt_kfactor() { return lepton_tree_obj.evt_kfactor(); }
	const float &gen_met() { return lepton_tree_obj.gen_met(); }
	const float &gen_metPhi() { return lepton_tree_obj.gen_metPhi(); }
	const float &njets() { return lepton_tree_obj.njets(); }
	const float &ht() { return lepton_tree_obj.ht(); }
	const float &ht_SS() { return lepton_tree_obj.ht_SS(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets() { return lepton_tree_obj.jets(); }
	const vector<float> &jets_disc() { return lepton_tree_obj.jets_disc(); }
	const vector<float> &jets_area() { return lepton_tree_obj.jets_area(); }
	const vector<float> &jets_undoJEC() { return lepton_tree_obj.jets_undoJEC(); }
	const TString &sample() { return lepton_tree_obj.sample(); }
	const int &nFOs_SS() { return lepton_tree_obj.nFOs_SS(); }
	const int &nvtx() { return lepton_tree_obj.nvtx(); }
	const float &rho() { return lepton_tree_obj.rho(); }
	const float &rho_neut_centr() { return lepton_tree_obj.rho_neut_centr(); }
	const float &rho_calo() { return lepton_tree_obj.rho_calo(); }
	const float &rho_calo_centr() { return lepton_tree_obj.rho_calo_centr(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &p4() { return lepton_tree_obj.p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &tag_p4() { return lepton_tree_obj.tag_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &dilep_p4() { return lepton_tree_obj.dilep_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &mc_p4() { return lepton_tree_obj.mc_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &mc_motherp4() { return lepton_tree_obj.mc_motherp4(); }
	const int &mc_motherid() { return lepton_tree_obj.mc_motherid(); }
	const int &id() { return lepton_tree_obj.id(); }
	const bool &isPF() { return lepton_tree_obj.isPF(); }
	const int &idx() { return lepton_tree_obj.idx(); }
	const float &dxyPV() { return lepton_tree_obj.dxyPV(); }
	const float &dZ() { return lepton_tree_obj.dZ(); }
	const float &dxyPV_err() { return lepton_tree_obj.dxyPV_err(); }
	const int &motherID() { return lepton_tree_obj.motherID(); }
	const int &mc_id() { return lepton_tree_obj.mc_id(); }
	const float &RelIso03() { return lepton_tree_obj.RelIso03(); }
	const float &RelIso03EA() { return lepton_tree_obj.RelIso03EA(); }
	const float &tag_RelIso03EA() { return lepton_tree_obj.tag_RelIso03EA(); }
	const float &RelIso03DB() { return lepton_tree_obj.RelIso03DB(); }
	const float &pfChargedHadronIso() { return lepton_tree_obj.pfChargedHadronIso(); }
	const float &pfPhotonIso() { return lepton_tree_obj.pfPhotonIso(); }
	const float &pfNeutralHadronIso() { return lepton_tree_obj.pfNeutralHadronIso(); }
	const float &tkIso() { return lepton_tree_obj.tkIso(); }
	const float &sumPUPt() { return lepton_tree_obj.sumPUPt(); }
	const bool &passes_SS_tight_v3() { return lepton_tree_obj.passes_SS_tight_v3(); }
	const bool &passes_SS_tight_noiso_v3() { return lepton_tree_obj.passes_SS_tight_noiso_v3(); }
	const bool &passes_SS_fo_v3() { return lepton_tree_obj.passes_SS_fo_v3(); }
	const bool &passes_SS_fo_noiso_v3() { return lepton_tree_obj.passes_SS_fo_noiso_v3(); }
	const bool &passes_SS_fo_looseMVA_v3() { return lepton_tree_obj.passes_SS_fo_looseMVA_v3(); }
	const bool &passes_SS_fo_looseMVA_noiso_v3() { return lepton_tree_obj.passes_SS_fo_looseMVA_noiso_v3(); }
	const bool &passes_SS_veto_v3() { return lepton_tree_obj.passes_SS_veto_v3(); }
	const bool &passes_SS_veto_noiso_v3() { return lepton_tree_obj.passes_SS_veto_noiso_v3(); }
	const bool &passes_SS_tight_v4() { return lepton_tree_obj.passes_SS_tight_v4(); }
	const bool &passes_SS_tight_noiso_v4() { return lepton_tree_obj.passes_SS_tight_noiso_v4(); }
	const bool &passes_SS_fo_v4() { return lepton_tree_obj.passes_SS_fo_v4(); }
	const bool &passes_SS_fo_noiso_v4() { return lepton_tree_obj.passes_SS_fo_noiso_v4(); }
	const bool &passes_SS_fo_looseMVA_v4() { return lepton_tree_obj.passes_SS_fo_looseMVA_v4(); }
	const bool &passes_SS_fo_looseMVA_noiso_v4() { return lepton_tree_obj.passes_SS_fo_looseMVA_noiso_v4(); }
	const bool &passes_SS_veto_v4() { return lepton_tree_obj.passes_SS_veto_v4(); }
	const bool &passes_SS_veto_noiso_v4() { return lepton_tree_obj.passes_SS_veto_noiso_v4(); }
	const bool &passes_SS_tight_v5() { return lepton_tree_obj.passes_SS_tight_v5(); }
	const bool &passes_SS_tight_noiso_v5() { return lepton_tree_obj.passes_SS_tight_noiso_v5(); }
	const bool &passes_SS_fo_v5() { return lepton_tree_obj.passes_SS_fo_v5(); }
	const bool &passes_SS_fo_noiso_v5() { return lepton_tree_obj.passes_SS_fo_noiso_v5(); }
	const bool &passes_SS_fo_looseMVA_v5() { return lepton_tree_obj.passes_SS_fo_looseMVA_v5(); }
	const bool &passes_SS_fo_looseMVA_noiso_v5() { return lepton_tree_obj.passes_SS_fo_looseMVA_noiso_v5(); }
	const bool &passes_SS_veto_v5() { return lepton_tree_obj.passes_SS_veto_v5(); }
	const bool &passes_SS_veto_noiso_v5() { return lepton_tree_obj.passes_SS_veto_noiso_v5(); }
	const bool &passes_WW_medium_v2() { return lepton_tree_obj.passes_WW_medium_v2(); }
	const bool &passes_WW_medium_noiso_v2() { return lepton_tree_obj.passes_WW_medium_noiso_v2(); }
	const bool &passes_WW_fo_v2() { return lepton_tree_obj.passes_WW_fo_v2(); }
	const bool &passes_WW_fo_noiso_v2() { return lepton_tree_obj.passes_WW_fo_noiso_v2(); }
	const bool &passes_WW_veto_v2() { return lepton_tree_obj.passes_WW_veto_v2(); }
	const bool &passes_WW_veto_noiso_v2() { return lepton_tree_obj.passes_WW_veto_noiso_v2(); }
	const bool &passes_HAD_veto_v3() { return lepton_tree_obj.passes_HAD_veto_v3(); }
	const bool &passes_HAD_veto_noiso_v3() { return lepton_tree_obj.passes_HAD_veto_noiso_v3(); }
	const bool &passes_HAD_loose_v3() { return lepton_tree_obj.passes_HAD_loose_v3(); }
	const bool &passes_HAD_loose_noiso_v3() { return lepton_tree_obj.passes_HAD_loose_noiso_v3(); }
	const bool &passes_POG_vetoID() { return lepton_tree_obj.passes_POG_vetoID(); }
	const bool &passes_POG_looseID() { return lepton_tree_obj.passes_POG_looseID(); }
	const bool &passes_POG_mediumID() { return lepton_tree_obj.passes_POG_mediumID(); }
	const bool &passes_POG_tightID() { return lepton_tree_obj.passes_POG_tightID(); }
	const bool &passes_VVV_cutbased_veto() { return lepton_tree_obj.passes_VVV_cutbased_veto(); }
	const bool &passes_VVV_cutbased_veto_noiso() { return lepton_tree_obj.passes_VVV_cutbased_veto_noiso(); }
	const bool &passes_VVV_cutbased_veto_noiso_noip() { return lepton_tree_obj.passes_VVV_cutbased_veto_noiso_noip(); }
	const bool &passes_VVV_cutbased_fo() { return lepton_tree_obj.passes_VVV_cutbased_fo(); }
	const bool &passes_VVV_cutbased_fo_noiso() { return lepton_tree_obj.passes_VVV_cutbased_fo_noiso(); }
	const bool &passes_VVV_cutbased_tight_noiso() { return lepton_tree_obj.passes_VVV_cutbased_tight_noiso(); }
	const bool &passes_VVV_cutbased_tight() { return lepton_tree_obj.passes_VVV_cutbased_tight(); }
	const bool &passes_VVV_MVAbased_tight_noiso() { return lepton_tree_obj.passes_VVV_MVAbased_tight_noiso(); }
	const bool &passes_VVV_MVAbased_tight() { return lepton_tree_obj.passes_VVV_MVAbased_tight(); }
	const bool &passes_VVV_baseline() { return lepton_tree_obj.passes_VVV_baseline(); }
	const float &ip3d() { return lepton_tree_obj.ip3d(); }
	const float &ip3derr() { return lepton_tree_obj.ip3derr(); }
	const int &type() { return lepton_tree_obj.type(); }
	const float &mt() { return lepton_tree_obj.mt(); }
	const float &ptrelv0() { return lepton_tree_obj.ptrelv0(); }
	const float &ptrelv1() { return lepton_tree_obj.ptrelv1(); }
	const float &miniiso() { return lepton_tree_obj.miniiso(); }
	const float &miniisoDB() { return lepton_tree_obj.miniisoDB(); }
	const float &reliso04() { return lepton_tree_obj.reliso04(); }
	const float &annulus04() { return lepton_tree_obj.annulus04(); }
	const float &AbsTrkIso() { return lepton_tree_obj.AbsTrkIso(); }
	const float &TrkAn04() { return lepton_tree_obj.TrkAn04(); }
	const float &iso03sumPt() { return lepton_tree_obj.iso03sumPt(); }
	const float &iso03emEt() { return lepton_tree_obj.iso03emEt(); }
	const float &iso03hadEt() { return lepton_tree_obj.iso03hadEt(); }
	const int &jet_close_lep_idx() { return lepton_tree_obj.jet_close_lep_idx(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet_close_lep() { return lepton_tree_obj.jet_close_lep(); }
	const float &jet_close_lep_undoJEC() { return lepton_tree_obj.jet_close_lep_undoJEC(); }
	const float &jet_close_lep_area() { return lepton_tree_obj.jet_close_lep_area(); }
	const float &jet_close_L1() { return lepton_tree_obj.jet_close_L1(); }
	const float &jet_close_L1nc() { return lepton_tree_obj.jet_close_L1nc(); }
	const float &jet_close_L1ncmc() { return lepton_tree_obj.jet_close_L1ncmc(); }
	const float &jet_close_L1L2L3() { return lepton_tree_obj.jet_close_L1L2L3(); }
	const float &jet_close_L2L3() { return lepton_tree_obj.jet_close_L2L3(); }
	const float &ptratio() { return lepton_tree_obj.ptratio(); }
	const int &tag_charge() { return lepton_tree_obj.tag_charge(); }
	const int &tag_mc_motherid() { return lepton_tree_obj.tag_mc_motherid(); }
	const float &tag_eSeed() { return lepton_tree_obj.tag_eSeed(); }
	const float &tag_eSCRaw() { return lepton_tree_obj.tag_eSCRaw(); }
	const float &tag_eSC() { return lepton_tree_obj.tag_eSC(); }
	const float &tag_ecalEnergy() { return lepton_tree_obj.tag_ecalEnergy(); }
	const int &exp_innerlayers() { return lepton_tree_obj.exp_innerlayers(); }
	const int &exp_outerlayers() { return lepton_tree_obj.exp_outerlayers(); }
	const int &tag_HLT_Ele27_eta2p1_WPTight_Gsf() { return lepton_tree_obj.tag_HLT_Ele27_eta2p1_WPTight_Gsf(); }
	const int &tag_HLT_Ele32_eta2p1_WPTight_Gsf() { return lepton_tree_obj.tag_HLT_Ele32_eta2p1_WPTight_Gsf(); }
	const int &tag_HLT_IsoMu24() { return lepton_tree_obj.tag_HLT_IsoMu24(); }
	const int &tag_HLT_IsoTkMu24() { return lepton_tree_obj.tag_HLT_IsoTkMu24(); }
	const float &dilep_mass() { return lepton_tree_obj.dilep_mass(); }
	const bool &isRandom() { return lepton_tree_obj.isRandom(); }
	const float &sigmaIEtaIEta_full5x5() { return lepton_tree_obj.sigmaIEtaIEta_full5x5(); }
	const float &sigmaIEtaIEta() { return lepton_tree_obj.sigmaIEtaIEta(); }
	const float &etaSC() { return lepton_tree_obj.etaSC(); }
	const float &dEtaIn() { return lepton_tree_obj.dEtaIn(); }
	const float &dPhiIn() { return lepton_tree_obj.dPhiIn(); }
	const float &hOverE() { return lepton_tree_obj.hOverE(); }
	const float &eSeed() { return lepton_tree_obj.eSeed(); }
	const float &scSeedEta() { return lepton_tree_obj.scSeedEta(); }
	const float &ecalEnergy() { return lepton_tree_obj.ecalEnergy(); }
	const float &eOverPIn() { return lepton_tree_obj.eOverPIn(); }
	const bool &conv_vtx_flag() { return lepton_tree_obj.conv_vtx_flag(); }
	const int &charge() { return lepton_tree_obj.charge(); }
	const int &sccharge() { return lepton_tree_obj.sccharge(); }
	const int &ckf_charge() { return lepton_tree_obj.ckf_charge(); }
	const bool &threeChargeAgree() { return lepton_tree_obj.threeChargeAgree(); }
	const float &mva() { return lepton_tree_obj.mva(); }
	const float &mva_25ns() { return lepton_tree_obj.mva_25ns(); }
	const float &tag_mva_25ns() { return lepton_tree_obj.tag_mva_25ns(); }
	const float &ecalIso() { return lepton_tree_obj.ecalIso(); }
	const float &hcalIso() { return lepton_tree_obj.hcalIso(); }
	const float &ecalPFClusterIso() { return lepton_tree_obj.ecalPFClusterIso(); }
	const float &hcalPFClusterIso() { return lepton_tree_obj.hcalPFClusterIso(); }
	const int &ckf_laywithmeas() { return lepton_tree_obj.ckf_laywithmeas(); }
	const float &sigmaIPhiIPhi_full5x5() { return lepton_tree_obj.sigmaIPhiIPhi_full5x5(); }
	const float &e1x5_full5x5() { return lepton_tree_obj.e1x5_full5x5(); }
	const float &e5x5_full5x5() { return lepton_tree_obj.e5x5_full5x5(); }
	const float &r9_full5x5() { return lepton_tree_obj.r9_full5x5(); }
	const float &tag_r9_full5x5() { return lepton_tree_obj.tag_r9_full5x5(); }
	const float &etaSCwidth() { return lepton_tree_obj.etaSCwidth(); }
	const float &phiSCwidth() { return lepton_tree_obj.phiSCwidth(); }
	const float &eSCRaw() { return lepton_tree_obj.eSCRaw(); }
	const float &eSC() { return lepton_tree_obj.eSC(); }
	const float &eSCPresh() { return lepton_tree_obj.eSCPresh(); }
	const float &ckf_chi2() { return lepton_tree_obj.ckf_chi2(); }
	const int &ckf_ndof() { return lepton_tree_obj.ckf_ndof(); }
	const float &chi2() { return lepton_tree_obj.chi2(); }
	const int &ndof() { return lepton_tree_obj.ndof(); }
	const float &fbrem() { return lepton_tree_obj.fbrem(); }
	const float &eOverPOut() { return lepton_tree_obj.eOverPOut(); }
	const float &dEtaOut() { return lepton_tree_obj.dEtaOut(); }
	const float &dPhiOut() { return lepton_tree_obj.dPhiOut(); }
	const int &gsf_validHits() { return lepton_tree_obj.gsf_validHits(); }
	const float &conv_vtx_prob() { return lepton_tree_obj.conv_vtx_prob(); }
	const int &pid_PFMuon() { return lepton_tree_obj.pid_PFMuon(); }
	const float &gfit_chi2() { return lepton_tree_obj.gfit_chi2(); }
	const int &gfit_validSTAHits() { return lepton_tree_obj.gfit_validSTAHits(); }
	const int &numberOfMatchedStations() { return lepton_tree_obj.numberOfMatchedStations(); }
	const int &validPixelHits() { return lepton_tree_obj.validPixelHits(); }
	const int &nlayers() { return lepton_tree_obj.nlayers(); }
	const float &chi2LocalPosition() { return lepton_tree_obj.chi2LocalPosition(); }
	const float &trkKink() { return lepton_tree_obj.trkKink(); }
	const int &validHits() { return lepton_tree_obj.validHits(); }
	const int &lostHits() { return lepton_tree_obj.lostHits(); }
	const float &segmCompatibility() { return lepton_tree_obj.segmCompatibility(); }
	const int &HLT_Mu8() { return lepton_tree_obj.HLT_Mu8(); }
	const int &HLT_Mu17() { return lepton_tree_obj.HLT_Mu17(); }
	const int &HLT_Mu8_TrkIsoVVL() { return lepton_tree_obj.HLT_Mu8_TrkIsoVVL(); }
	const int &HLT_Mu17_TrkIsoVVL() { return lepton_tree_obj.HLT_Mu17_TrkIsoVVL(); }
	const int &HLT_IsoMu24() { return lepton_tree_obj.HLT_IsoMu24(); }
	const int &HLT_IsoTkMu24() { return lepton_tree_obj.HLT_IsoTkMu24(); }
	const int &HLT_Mu50() { return lepton_tree_obj.HLT_Mu50(); }
	const int &HLT_Mu55() { return lepton_tree_obj.HLT_Mu55(); }
	const int &HLT_TkMu50() { return lepton_tree_obj.HLT_TkMu50(); }
	const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg() { return lepton_tree_obj.HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg() { return lepton_tree_obj.HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg() { return lepton_tree_obj.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg() { return lepton_tree_obj.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &HLT_Ele8_CaloIdM_TrackIdM_PFJet30() { return lepton_tree_obj.HLT_Ele8_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele12_CaloIdM_TrackIdM_PFJet30() { return lepton_tree_obj.HLT_Ele12_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele17_CaloIdM_TrackIdM_PFJet30() { return lepton_tree_obj.HLT_Ele17_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele23_CaloIdM_TrackIdM_PFJet30() { return lepton_tree_obj.HLT_Ele23_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30() { return lepton_tree_obj.HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30() { return lepton_tree_obj.HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30() { return lepton_tree_obj.HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30() { return lepton_tree_obj.HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele27_eta2p1_WPTight_Gsf() { return lepton_tree_obj.HLT_Ele27_eta2p1_WPTight_Gsf(); }
	const int &HLT_Ele32_eta2p1_WPTight_Gsf() { return lepton_tree_obj.HLT_Ele32_eta2p1_WPTight_Gsf(); }
	const int &HLT_Ele105_CaloIdVT_GsfTrkIdT() { return lepton_tree_obj.HLT_Ele105_CaloIdVT_GsfTrkIdT(); }
	const int &HLT_Ele115_CaloIdVT_GsfTrkIdT() { return lepton_tree_obj.HLT_Ele115_CaloIdVT_GsfTrkIdT(); }
	const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_LeadingLeg() { return lepton_tree_obj.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_LeadingLeg(); }
	const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_TrailingLeg() { return lepton_tree_obj.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_TrailingLeg(); }
	const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_L1() { return lepton_tree_obj.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_L1(); }
	const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL() { return lepton_tree_obj.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL(); }
	const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_LeadingLeg() { return lepton_tree_obj.HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_LeadingLeg(); }
	const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_TrailingLeg() { return lepton_tree_obj.HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_TrailingLeg(); }
	const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_L1() { return lepton_tree_obj.HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_L1(); }
	const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL() { return lepton_tree_obj.HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL(); }
}
